Add release GH Action
taranis-ai/taranis-ai pull request #242
Opened 2024-06-23 13:47 UTC by not4Pedro

2024-06-25 09:25 UTC, b3n4kh commented on .github/workflows/release.yaml
> +
Tags always include a tar of the code so this is obsolete, and should be removed

2024-06-26 12:06 UTC, b3n4kh requested changes

2024-06-26 12:06 UTC, b3n4kh commented on .github/workflows/release.yaml
> +      - '*'
`[0-9]+.[0-9]+.[0-9]+`

2024-07-15 12:17 UTC, b3n4kh commented on .github/workflows/release.yaml
> +      #       ${{ runner.temp }}/${{ env.tag }}.tar.gz
remove these two lines

2024-07-16 17:03 UTC, not4Pedro commented
This workflow created this release https://github.com/not4Pedro/taranis-test-release/releases/tag/0.0.3 
It prepends the multiline `tag_message` to a full change log. 
If no tag message is provided, it falls back to the last commit message (by design).
The release name is implicitly taken from the pushed tag.

2024-07-17 08:33 UTC, merged