Add sentry to Core and SQLAlchemy
taranis-ai/taranis-ai pull request #287
Opened 2024-07-17 12:21 UTC by not4Pedro

Add sentry to Core and SQLAlchemy

2024-07-17 12:44 UTC, not4Pedro commented on src/core/core/__init__.py
> +    )
the default return value of `os.getenv` is None, Sentry handles this by not sending any requests to Sentry

2024-07-17 12:51 UTC, not4Pedro commented on src/core/core/__init__.py
> +
@b3n4kh okay, as per example, sentry starts before that app, but apparently that's not mandatory. I will do

2024-07-17 13:19 UTC, b3n4kh requested changes

2024-07-17 13:19 UTC, b3n4kh commented on src/core/core/__init__.py
> +    sentry_manager.initialize(app)
should be one of the first things, to get logs if anything during initialization fails

2024-07-17 13:19 UTC, b3n4kh commented on src/core/core/managers/sentry_manager.py
> +        # We recommend adjusting this value in production.
Remove copy/pasted comments

2024-07-22 10:50 UTC, b3n4kh requested changes

2024-07-22 10:50 UTC, b3n4kh commented on docker/compose.yml
> +      TARANIS_SENTRY_DSN: "${TARANIS_GUI_SENTRY_DSN:-}"
change both to: `TARANIS_GUI_SENTRY_DSN`

2024-07-22 10:50 UTC, b3n4kh commented on docker/compose.yml
> +      SENTRY_DSN: "${TARANIS_CORE_SENTRY_DSN:-}"
change both to: `TARANIS_CORE_SENTRY_DSN`

2024-07-22 14:11 UTC, merged